spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: true

    sql:
      init:
        mode: always